{% set name = "oliver" %}
{% set pip_name = "stjudecloud-oliver" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pip_name[0] }}/{{ pip_name }}/{{ pip_name }}-{{ version }}.tar.gz
  sha256: 654e8cb661f63071a30612d53eaa98799c6d9453f3d22a9450fa6c82f161227a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.0, <3.8
    - poetry >=1.0.3
  run:
    - python >=3.0, <3.8
    - aiohttp ==3.6.2
    - azure-cosmos ==3.1.2
    - boto3 ==1.11.9
    - logzero ==1.5.0
    - pendulum ==2.0.5
    - requests ==2.22.0
    - tabulate ==0.8.6
    - tzlocal ==2.0.0

test:
  imports:
    - oliver
  commands:
    - oliver --help

about:
  home: https://github.com/stjudecloud/oliver
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: An opinionated Cromwell orchestration manager.
  doc_url: https://github.com/stjudecloud/oliver/blob/master/README.md
  dev_url: https://github.com/stjudecloud/oliver/blob/master/docs/DEVELOPMENT.md

extra:
  recipe-maintainers:
    - claymcleod
